import os
import glob

def extract_boards(sok_file):
    with open(sok_file, 'r') as f:
        content = f.read()
    boards = []
    current_board = []
    for line in content.split('\n'):
        if line.startswith('#') or (line.strip().startswith('#') and '#' in line):
            current_board.append(line)
        elif line.strip() == '' and current_board:
            boards.append('\n'.join(current_board))
            current_board = []
    if current_board:
        boards.append('\n'.join(current_board))
    return boards

def gather_boards(input_dir, output_file, max_boards=40):
    sok_files = []
    for root, dirs, files in os.walk(input_dir):
        for file in files:
            if file.endswith('.sok'):
                sok_files.append(os.path.join(root, file))
    
    sok_files.sort(key=os.path.getmtime, reverse=True)
    
    gathered = 0
    all_boards = []
    for sok_file in sok_files:
        boards = extract_boards(sok_file)
        for board in boards:
            if gathered >= max_boards:
                break
            all_boards.append(board)
            gathered += 1
        if gathered >= max_boards:
            break

    with open(output_file, 'w') as out_f:
        for idx, board_content in enumerate(all_boards):
            out_f.write(f"\n{idx+1} - AutoGenerated - {idx+1}\n")
            out_f.write(board_content + "\n\n")
            
    print(f"Gathered {gathered} boards into {output_file}")

if __name__ == '__main__':
    gather_boards('sokoban_dataset_buckets', 'sok_files/auto_generated.sok', max_boards=40)
